/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("AgeRatingObjectPageObjectPage journey");

        opaTest("Navigate to AgeRatingObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheAgeRatingListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheAgeRatingListGenerated.onTable().iCheckRows();
            When.onTheAgeRatingListGenerated.onTable().iPressRow(0);

            Then.onTheAgeRatingObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the FieldGroup::AgeRating section of the Object Page", function (_Given, _When, Then) {
            Then.onTheAgeRatingObjectPageGenerated.iCheckSection({ section: "FieldGroup::AgeRating" });
            Then.onTheAgeRatingObjectPageGenerated.onForm({ section: "FieldGroup::AgeRating" }).iCheckField({ property: "code" });
            Then.onTheAgeRatingObjectPageGenerated.onForm({ section: "FieldGroup::AgeRating" }).iCheckField({ property: "name" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});