/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ReviewObjectPageObjectPage journey");

        opaTest("Navigate to ReviewObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheReviewListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheReviewListGenerated.onTable().iCheckRows();
            When.onTheReviewListGenerated.onTable().iPressRow(0);

            Then.onTheReviewObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the Facets::0 section of the Object Page", function (_Given, _When, Then) {
            Then.onTheReviewObjectPageGenerated.iCheckSection({ section: "Facets::0" });
            Then.onTheReviewObjectPageGenerated.onForm({ section: "Facets::0" }).iCheckField({ property: "reviewId" });
            Then.onTheReviewObjectPageGenerated.onForm({ section: "Facets::0" }).iCheckField({ property: "name" });
            Then.onTheReviewObjectPageGenerated.onForm({ section: "Facets::0" }).iCheckField({ property: "rate" });
            Then.onTheReviewObjectPageGenerated.onForm({ section: "Facets::0" }).iCheckField({ property: "comment" });
            Then.onTheReviewObjectPageGenerated.onForm({ section: "Facets::0" }).iCheckField({ property: "createdAt" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});