/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("GameObjectPageObjectPage journey");

        opaTest("Navigate to GameObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheGameListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheGameListGenerated.onTable().iCheckRows();
            When.onTheGameListGenerated.onTable().iPressRow(0);

            Then.onTheGameObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the number of sections of the Object Page", function (_Given, _When, Then) {
            Then.onTheGameObjectPageGenerated.iCheckNumberOfSections(6);
        });

        opaTest("Check the FieldGroup::GameDetails section of the Object Page", function (_Given, When, Then) {
            When.onTheGameObjectPageGenerated.iGoToSection({ section: "FieldGroup::GameDetails" });
            Then.onTheGameObjectPageGenerated.iCheckSection({ section: "FieldGroup::GameDetails" });
            Then.onTheGameObjectPageGenerated.onForm({ section: "FieldGroup::GameDetails" }).iCheckField({ property: "gameId" });
            Then.onTheGameObjectPageGenerated.onForm({ section: "FieldGroup::GameDetails" }).iCheckField({ property: "title" });
            Then.onTheGameObjectPageGenerated.onForm({ section: "FieldGroup::GameDetails" }).iCheckField({ property: "releaseDate" });
            Then.onTheGameObjectPageGenerated.onForm({ section: "FieldGroup::GameDetails" }).iCheckField({ property: "price" });
            Then.onTheGameObjectPageGenerated.onForm({ section: "FieldGroup::GameDetails" }).iCheckField({ property: "rating" });
            Then.onTheGameObjectPageGenerated.onForm({ section: "FieldGroup::GameDetails" }).iCheckField({ property: "stock" });
            Then.onTheGameObjectPageGenerated.onForm({ section: "FieldGroup::GameDetails" }).iCheckField({ property: "stockStatus" });
            Then.onTheGameObjectPageGenerated.onForm({ section: "FieldGroup::GameDetails" }).iCheckField({ property: "imgUrl" });
            Then.onTheGameObjectPageGenerated.onForm({ section: "FieldGroup::GameDetails" }).iCheckField({ property: "description" });
        });

        opaTest("Check the FieldGroup::AssociatedEntity section of the Object Page", function (_Given, When, Then) {
            When.onTheGameObjectPageGenerated.iGoToSection({ section: "FieldGroup::AssociatedEntity" });
            Then.onTheGameObjectPageGenerated.iCheckSection({ section: "FieldGroup::AssociatedEntity" });
            Then.onTheGameObjectPageGenerated.onForm({ section: "FieldGroup::AssociatedEntity" }).iCheckField({ property: "publisher_publisherId" });
            Then.onTheGameObjectPageGenerated.onForm({ section: "FieldGroup::AssociatedEntity" }).iCheckField({ property: "studio_studioId" });
            Then.onTheGameObjectPageGenerated.onForm({ section: "FieldGroup::AssociatedEntity" }).iCheckField({ property: "agerating_code" });
        });

        opaTest("Check the gameplatforms::LineItem section of the Object Page", function (_Given, When, Then) {
            When.onTheGameObjectPageGenerated.iGoToSection({ section: "gameplatforms::LineItem" });
            Then.onTheGameObjectPageGenerated.iCheckSection({ section: "gameplatforms::LineItem" });
        });

        opaTest("Check the categories::LineItem section of the Object Page", function (_Given, When, Then) {
            When.onTheGameObjectPageGenerated.iGoToSection({ section: "categories::LineItem" });
            Then.onTheGameObjectPageGenerated.iCheckSection({ section: "categories::LineItem" });
        });

        opaTest("Check the screenshots::LineItem section of the Object Page", function (_Given, When, Then) {
            When.onTheGameObjectPageGenerated.iGoToSection({ section: "screenshots::LineItem" });
            Then.onTheGameObjectPageGenerated.iCheckSection({ section: "screenshots::LineItem" });
        });

        opaTest("Check the reviews::LineItem section of the Object Page", function (_Given, When, Then) {
            When.onTheGameObjectPageGenerated.iGoToSection({ section: "reviews::LineItem" });
            Then.onTheGameObjectPageGenerated.iCheckSection({ section: "reviews::LineItem" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});